# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Black Duck Security Action allows you to integrate Static Analysis Security Testing (SAST) and Software Composition Analysis (SCA) into your CI/CD pipelines.
# For more information about configuring your workflow,
# read our documentation at https://github.com/blackduck-inc/black-duck-security-scan

name: CI Black Duck security scan

on:
  push:
    branches: [ "main", "secure-build" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "secure-build" ]
  schedule:
    - cron: '34 5 * * 6'

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read

    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Black Duck SCA scan
        id: black-duck-full-scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: blackduck-inc/black-duck-security-scan@152247222aa9cd38124acd5c0cf60f4db71adc3f # v2.11.0
        with:
          ### ---------- BLACKDUCK SCA SCANNING: REQUIRED FIELDS ----------
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_scan_full: true

          ### SCANNING: Optional fields
          # blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
          detect_args: "--detect.accuracy.required=NONE"

          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          blackducksca_fixpr_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled

          ### PULL REQUEST COMMENTS: Uncomment below to enable
          blackducksca_prcomment_enabled: true 
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          blackducksca_reports_sarif_create: true # Create Black Duck SCA SARIF report and upload it as artifact
          blackducksca_upload_sarif_report: true  # Upload Black Duck SCA SARIF report in GitHub Advanced Security tab
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackducksca_upload_sarif_report is set as true

          ### Mark build status if policy violating issues are found
          mark_build_status: 'success'

          ### To enable Black Duck SCA policy badges
          blackducksca_policy_badges_create: true
          blackducksca_policy_badges_maxCount: 5

          ### Uncomment below configuration if Bridge diagnostic files needs to be uploaded
          include_diagnostics: true
          
      - name: Black Duck SCA PR Scan
        id: black-duck-pr-scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: blackduck-inc/black-duck-security-scan@152247222aa9cd38124acd5c0cf60f4db71adc3f # v2.11.0
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_scan_full: false
          detect_args: "--detect.accuracy.required=NONE"

          ### Mark build status if policy violating issues are found
          mark_build_status: 'success'
          
          ### ---------- COVERITY SCANNING: REQUIRED FIELDS ----------
          ### coverity_url: ${{ vars.COVERITY_URL }}
          ### coverity_user: ${{ secrets.COVERITY_USER }}
          ### coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}

          ### ---------- POLARIS SCANNING: REQUIRED FIELDS ----------
          ### polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          ### polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          ### polaris_assessment_types: "SCA,SAST"

          ### ---------- SRM SCANNING: REQUIRED FIELDS ----------
          ### srm_url: ${{ vars.SRM_URL }}
          ### srm_apikey: ${{ secrets.SRM_API_KEY }}
          ### srm_assessment_types: "SCA,SAST"
